// ==UserScript==
// @name           Cities Do That Thing
// @namespace      http://potatoengineer.110mb.com/
// @description    Creates links for default actions on items you acquire.
// @include        http://cities.totl.net/cgi-bin/game*
// @include        http://carmilla.ecs.soton.ac.uk:8080/cgi-bin/game*
// @require	http://potatoengineer.110mb.com/cities_potatolibrary.user.js
//
// Version 1.01: PotatoLibrary update: item list update, recursive PotatoConsole placement.
//
// Version 1.0: creates links for holding/using/equipping items you acquire.  Only shows valid links, though I don't guarantee 100% accuracy.
// ==/UserScript==

GM_setValue('scriptVersion','1.01');

var internals;
var usableEquip;

checkUpdates('Do That Thing!','dothing','cities_do_that_thing.user.js');
createInterface();
createLinks();

function createInterface() {
	var box = makeBox("Do That Thing:");
	var div=document.createElement('div');
	div.appendChild(makeCheckbox('showHold','Show links to hold items',true));
	box.appendChild(div);
	div=document.createElement('div');
	div.appendChild(makeCheckbox('showUse','Show links to use items',true));
	box.appendChild(div);
	div=document.createElement('div');
	div.appendChild(makeCheckbox('showEquip','Show links to equip items',true));
	box.appendChild(div);
	insertAt(box,GM_getValue('display_location','PotatoConsole'));
	
	box.appendChild(locationSelect());
	
}

function createLinks() {
	var messages=$('messages');
	var item;
	if (isNewfangled()) {
		for (var n=messages.firstChild;n && n!=null;n=n.nextSibling) {
			if (n.nodeType==3){	//text node
				item=parseGainedItem(n.nodeValue);
				if (item) {
					n=n.nextSibling;
					if (GM_getValue('showHold',true)) {
						messages.insertBefore(makeLink('hold',item),n);
					}
					if (isUsable(item) && GM_getValue('showUse',true)) {
						messages.insertBefore(makeLink('use',item),n);
					}
					if (isEquip(item) && GM_getValue('showEquip',true)) {
						messages.insertBefore(makeLink('equip',item),n);
						messages.insertBefore(makeLink('equipall',item),n);
					}
				}
				if (n==null) break;
			}
		}
	}
	else {
		messages=messages.innerHTML.split("\n");
		GM_log(messages);
		var linkBox=document.createElement('div');
		for (var i=0;i<messages.length;i++) {
			item=parseGainedItem(messages[i], true);
			if (item) {
				if (GM_getValue('showHold',true)) {
					linkBox.appendChild(makeLink('hold',item.code,item.name));
				}
				if (isUsable(item.code) && GM_getValue('showUse',true)) {
					linkBox.appendChild(makeLink('use',item.code,item.name));
				}
				if (isEquip(item.code) && GM_getValue('showEquip',true)) {
					linkBox.appendChild(makeLink('equip',item.code,item.name));
					linkBox.appendChild(makeLink('equipall',item.code,item.name));
				}
			}
		}
		if (linkBox.hasChildNodes()) {
			$('messages').parentNode.appendChild(linkBox);
		}
	}
}
function makeLink(command, item, label) {
	var span=document.createElement('span');
	var link=document.createElement('a');
	link.href='?item='+item+(command!='hold'?'&act_item_'+command+'=1':'');
	link.appendChild(document.createTextNode(command[0].toUpperCase()+command.substring(1)+(label?' '+label:'')));
	span.appendChild(link);
	span.appendChild(document.createTextNode(' '));
	return span;
}

function parseGainedItem(inputLine, useBaseName) {
	var itemRE=/^You gain (an? |\d+ )(Glowing )?(.+)\.$/;
	var itemResult=itemRE.exec(inputLine);
	var itemCount=1;
	if (itemResult) {
		itemCount=parseInt(itemResult[1]);
		if (isNaN(itemCount)) itemCount=1;
		
		var item=itemResult[3];
		if (itemCount>1) item=depluralize(item);
		var itemCode=internalName(item);
		GM_log('parseGainedItem:'+item);
		if (useBaseName) return {'name':item,'code':itemCode};
		else return itemCode;
	}
	return false;
}

function internalName(itemName) {
	if (!internals) {
		internals= {
			"'Bard Goggles":"BardGoggles",
			"2 Iron":"Iron2",
			"3 Iron":"Iron3",
			"4 Iron":"Iron4",
			"5 Iron":"Iron5",
			"6 Iron":"Iron6",
			"7 Iron":"Iron7",
			"8 Iron":"Iron8",
			"9 Iron":"Iron9",
			"A Bomb in a Ball":"AbominaBall",
			"A bit put-out Bow":"CrossBow1",
			"Abcdefghijklmnopqrstuvwxy":"CustomWeapon.15859",
			"Accordion":"InstrumentAccordion",
			"Acle":"P1",
			"After-Dinner Mint":"MintSweet",
			"Alchemy Spell":"SpellGold",
			"Align Air Spell":"SpellAlignAir",
			"Align All to Air Spell":"SpellAlignAllAir",
			"Align All to Earth Spell":"SpellAlignAllEarth",
			"Align All to Fire Spell":"SpellAlignAllFire",
			"Align All to Water Spell":"SpellAlignAllWater",
			"Align Area to Air Spell":"SpellAlignAreaAir",
			"Align Area to Earth Spell":"SpellAlignAreaEarth",
			"Align Area to Fire Spell":"SpellAlignAreaFire",
			"Align Area to Water Spell":"SpellAlignAreaWater",
			"Align Earth Spell":"SpellAlignEarth",
			"Align Fire Spell":"SpellAlignFire",
			"Align Water Spell":"SpellAlignWater",
			"All or Nothing Spell":"SpellDam25b",
			"Amok Spell":"SpellDam25c",
			"Angry Bow":"CrossBow4",
			"Annoyance":"PeeveEgg",
			"Annoyed Bow":"CrossBow2",
			"Annoying Plastic Thing":"PlasticThing",
			"Anti-Hista":"AntiHista",
			"Archers Charm Spell":"SpellHit40b",
			"Archers Luck Spell":"SpellHit40a",
			"Army Boot":"LeatherBoot",
			"Astral Plain Spell":"SpellAstral",
			"Augers Aim Spell":"SpellHit60c",
			"B.B. Gun":"BBGun",
			"Bag (Kit for Beginners)":"Bag.8030",
			"Bag of Cocoa Powder":"CocoaPowder",
			"Bag of Coffee Beans":"CoffeeBeans",
			"Bag of Flour":"Flour",
			"Bag of Grain Mash":"GrainMash",
			"Bag of Ground Coffee":"GroundCoffee",
			"Bag of Roasted Coffee Beans":"RoastedCoffeeBeans",
			"Bag of Walnuts":"Walnuts",
			"Ball Invitation":"BallInvite",
			"Ball of Wool":"WoolLong",
			"Bashing Stuff Spell":"SpellDam2a",
			"Basket of Crushed Plums":"CrushedPlums",
			"Basket of Dried Figs":"DriedFigs",
			"Basket of Dried Plums":"DriedPlums",
			"Basket of Figs":"Figs",
			"Basket of Plums":"Plums",
			"Bauhaus T-Shirt":"ShirtBauhaus",
			"Become Air Spell":"SpellAlignSelfAir",
			"Become Earth Spell":"SpellAlignSelfEarth",
			"Become Fire Spell":"SpellAlignSelfFire",
			"Become Water Spell":"SpellAlignSelfWater",
			"Beef Steak":"Beef",
			"Big Blue India-Rubber Ball":"BlueBall",
			"Big Piece of Chalk":"BigChalk",
			"Big Red India-Rubber Ball":"BouncyBall",
			"Bilbo Cocktail":"HobbitCocktailBilbo",
			"Bind Elemental Spell":"SpellBind",
			"Bind Spirit Spell":"SpellBind2",
			"Bit of Bronze":"Bronze",
			"Bit of Copper":"Copper",
			"Bit of Iron":"Iron",
			"Bit of Lead":"Lead",
			"Bit of Misril":"Misril",
			"Bit of Molten Glass":"Glass",
			"Bit of Parchment":"ClueSpace",
			"Bit of Silver":"Silver",
			"Bit of Zinc":"Zinc",
			"Black Eye Liners":"BlackEyeLiner",
			"Blacksmith's Tongs":"SmithTongs",
			"Bo Staff":"Staff",
			"Boniface Potion":"PotionCure4",
			"Book (Level 1 spell book)":"SpellBook.19851",
			"Book (Level 2 spell book)":"SpellBook.19867",
			"Book (Level 3 spell book)":"SpellBook.22868",
			"Bottle of Anisette":"Anisette",
			"Bottle of Brandy":"Brandy",
			"Bottle of Cheap Rose":"Rose",
			"Bottle of Coconut Milk":"CoconutMilk",
			"Bottle of Creme de Cacao":"CremeDeCacao",
			"Bottle of Creme de Menthe":"CremeDeMenthe",
			"Bottle of Dragon Fruit Juice":"DragonFruitJuice",
			"Bottle of Gin":"Gin",
			"Bottle of Ginger Wine":"GingerWine",
			"Bottle of Grenadine":"Grenadine",
			"Bottle of Grog":"Grog",
			"Bottle of Herb Liqueur":"HerbLiqueur",
			"Bottle of Kahlua":"Kahlua",
			"Bottle of Lemon Juice":"LemonJuice",
			"Bottle of Lemonade":"Lemonade",
			"Bottle of Lime Juice":"LimeJuice",
			"Bottle of Olive Oil":"OliveOil",
			"Bottle of Orange Juice":"OrangeJuice",
			"Bottle of Pepper Sauce":"PepperSauce",
			"Bottle of Pineapple Juice":"PineappleJuice",
			"Bottle of Romulan Ale":"RomulanAle",
			"Bottle of Rum":"Rum",
			"Bottle of Saurian Brandy":"SaurianBrandy",
			"Bottle of Sloe Gin":"SloeGin",
			"Bottle of Sparkling Water":"FizzyWater",
			"Bottle of Sparkling Wine":"FizzyWine",
			"Bottle of Tequila":"Tequila",
			"Bottle of Tomato Juice":"TomatoJuice",
			"Bottle of Tonic Water":"TonicWater",
			"Bottle of Triple Sec":"TripleSec",
			"Bottle of Vermouth":"Vermouth",
			"Bottle of Vinegar":"Vinegar",
			"Bottle of Vodka":"Vodka",
			"Bottle of Whisky":"Whisky",
			"Bowl of Irish Stew":"IrishStew",
			"Box of Parts":"AcmeBox",
			"Brak Potion":"PotionCure8",
			"Brand New Dog Bot":"NewDogBot",
			"Brand New Electric Sheep":"NewElectricSheep",
			"Breakfast Club Sandwich":"ClubSandwich",
			"Bronze Scale Armour":"BronzeScale",
			"Bucket of Busy Planckton":"BusyEWool.27326",
			"Bucket of Planckton":"Planckton",
			"Bunch of Grapes":"Grapes",
			"Can of Lager":"Lager",
			"Can of Primordial Soup":"PrimordialSoup",
			"Can of Red Bull":"RedBull",
			"Caravel (in a bottle)":"Caravel",
			"Caravel with hole (in a bottle)":"CaravelHoled",
			"Card (Guild Treasury Card)":"GuildCard.19402",
			"Card: Death":"Tarot13",
			"Card: Judgement":"Tarot20",
			"Card: Justice":"Tarot11",
			"Card: Strength":"Tarot8",
			"Card: Temperance":"Tarot14",
			"Card: The Chariot":"Tarot7",
			"Card: The Devil":"Tarot15",
			"Card: The Emperor":"Tarot4",
			"Card: The Empress":"Tarot3",
			"Card: The Fool":"Tarot0",
			"Card: The Hanged Man":"Tarot12",
			"Card: The Hermit":"Tarot9",
			"Card: The Hierophant":"Tarot5",
			"Card: The High Priestess":"Tarot2",
			"Card: The Lovers":"Tarot6",
			"Card: The Magician":"Tarot1",
			"Card: The Moon":"Tarot18",
			"Card: The Star":"Tarot17",
			"Card: The Sun":"Tarot19",
			"Card: The Tower":"Tarot16",
			"Card: The Wheel of Fortune":"Tarot10",
			"Card: The World":"Tarot21",
			"Cat'o'eight Tails":"CatO8Tails",
			"Cat'o'five Tails":"CatO5Tails",
			"Cat'o'four Tails":"CatO4Tails",
			"Cat'o'nine Tails":"CatO9Tails",
			"Cat'o'seven Tails":"CatO7Tails",
			"Cat'o'six Tails":"CatO6Tails",
			"Cat'o'three Tails":"CatO3Tails",
			"Cat'o'two Tails":"CatO2Tails",
			"Chillwell Potion":"PotionCure1",
			"Chocolate Bombe":"IceCreamChocolateBombe",
			"Christmas Cracker":"Cracker",
			"Clean Bandage":"Bandage",
			"Clear Spell":"SpellClear",
			"Climbing Gear":"Climb",
			"Cloak of Invisibility":"InvisCloak",
			"Clock of Invisibility":"InvisClock",
			"Clove of Garlic":"Garlic",
			"Club 18-30":"Club1830",
			"Coloured Scarf":"ScarfShort",
			"Compressed Air Spell":"SpellWandAir1",
			"Compressed Earth Spell":"SpellWandEarth1",
			"Compressed Fire Spell":"SpellWandFire1",
			"Compressed Water Spell":"SpellWandWater1",
			"Contract Palantir":"Palantir",
			"Cool Disguise":"SpockEars",
			"Copper Axe (Treeman bane)":"Bane.14566",
			"Copy of 'All the Things She Said'":"Pop00",
			"Copy of 'Atomic'":"Pop01",
			"Copy of 'Beautiful'":"Pop02",
			"Copy of 'Believe'":"Pop03",
			"Copy of 'Dancing Queen'":"Pop04",
			"Copy of 'Diamonds Are Forever'":"Pop06",
			"Copy of 'Diamonds Are a Girl's Best Friend'":"Pop05",
			"Copy of 'Dirrty'":"Pop07",
			"Copy of 'Express Yourself'":"Pop08",
			"Copy of 'G.A.Y.'":"Pop09",
			"Copy of 'Gimme! Gimme! Gimme! (A Man After Midnight)'":"Pop10",
			"Copy of 'Girls Just Want to Have Fun'":"Pop11",
			"Copy of 'Go West'":"Pop12",
			"Copy of 'I Will Survive'":"Pop13",
			"Copy of 'I'm Coming Out'":"Pop14",
			"Copy of 'I'm Still Standing'":"Pop15",
			"Copy of 'It's Raining Men'":"Pop17",
			"Copy of 'It's a Sin'":"Pop16",
			"Copy of 'Lady Marmalade'":"Pop18",
			"Copy of 'Like I Love You'":"Pop19",
			"Copy of 'Love at First Sight'":"Pop20",
			"Copy of 'Macho Man'":"Pop21",
			"Copy of 'Mamma Mia'":"Pop22",
			"Copy of 'Man! I Feel Like A Woman!'":"Pop23",
			"Copy of 'Over the Rainbow'":"Pop24",
			"Copy of 'Relax'":"Pop25",
			"Copy of 'Strong Enough'":"Pop26",
			"Copy of 'Vogue'":"Pop27",
			"Copy of 'Where Is My Man'":"Pop28",
			"Copy of 'Y.M.C.A.'":"Pop29",
			"Copy of 'You Spin Me Round (Like a Record)'":"Pop31",
			"Copy of 'Your Disco Needs You'":"Pop30",
			"Copy of Battlefield Earth":"BattlefieldEarth",
			"Copy of Between Planets":"HBook6",
			"Copy of Beyond This Horizon":"HBook0",
			"Copy of Citizen of the Galaxy":"HBook15",
			"Copy of Double Star":"HBook13",
			"Copy of Farmer in the Sky":"HBook5",
			"Copy of Farnham's Freehold":"HBook23",
			"Copy of Friday":"HBook28",
			"Copy of Glory Road":"HBook22",
			"Copy of Have Space Suit - Will Travel":"HBook17",
			"Copy of I Will Fear No Evil":"HBook25",
			"Copy of Job: A Comedy of Justice":"HBook29",
			"Copy of Methuselah's Children":"HBook18",
			"Copy of Podkayne of Mars":"HBook21",
			"Copy of Red Planet":"HBook3",
			"Copy of Rocket Ship Galileo":"HBook1",
			"Copy of Sixth Column":"HBook4",
			"Copy of Space Cadet":"HBook2",
			"Copy of Starman Jones":"HBook9",
			"Copy of Starship Troopers":"HBook19",
			"Copy of Stranger in a Strange Land":"HBook20",
			"Copy of The Cat Who Walks Through Walls":"HBook30",
			"Copy of The Citizen":"Newspaper",
			"Copy of The Door into Summer":"HBook16",
			"Copy of The Moon Is a Harsh Mistress":"HBook24",
			"Copy of The Number of the Beast":"HBook27",
			"Copy of The Puppet Masters":"HBook7",
			"Copy of The Rolling Stones":"HBook8",
			"Copy of The Star Beast":"HBook10",
			"Copy of Time Enough for Love":"HBook26",
			"Copy of Time for the Stars":"HBook14",
			"Copy of To Sail Beyond the Sunset":"HBook31",
			"Copy of Tunnel in the Sky":"HBook11",
			"Copy of Variable Star":"HBook12",
			"Corpse of Yes":"Corpse.26592",
			"Crackle Spell":"SpellCrackle",
			"Crispy Shredded Duck Bit":"CrispyDuck",
			"Critical Healing Spell":"SpellHeal40c",
			"Crocodile Scale":"Scale",
			"Cross Bow":"CrossBow3",
			"Crumhorn":"InstrumentCrumhorn",
			"Crushed Bunch of Grapes":"CrushedGrapes",
			"Cup of Tea":"Tea",
			"Cursed Rainbow Glass Vorpal Blade Of You Spin Me Right Round":"CRGVBOYSMRR",
			"Cute Seal Cheese":"OtherDairy.32462",
			"Daemonic Chain Saw":"Demon6",
			"Daemonic Chainsaw Nunchucks":"DemonNC",
			"Daemonic Dagger":"Demon2",
			"Daemonic Great Sword":"Demon5",
			"Daemonic Knife":"Demon3",
			"Daemonic Letter Opener":"Demon1",
			"Daemonic Sword":"Demon4",
			"Dark Bow":"GothBow",
			"Dark Catana":"GothCatana",
			"Dark Knife":"GothKnife",
			"Dark Stone":"GothStone",
			"Dark Sword":"GothSword",
			"Dark Sword2":"GothSword2",
			"Dark Talisman":"GothTalisman",
			"Dark Wand":"GothWand",
			"Dark Wand2":"GothWand2",
			"Dark Wand3":"GothWand3",
			"Darken Spell":"SpellDark",
			"Death Wand":"DeathWandZero",
			"Devilishly Clever Trap":"RRTrap",
			"Dharma Potion":"PotionCure6",
			"Diamond Team Ring (Team Small Sand Worm)":"TeamRing.16939",
			"Didgeridoo":"InstrumentDidgeridoo",
			"Dissolution Spell":"SpellDissolve",
			"Dose of Antidote":"Antidote",
			"Dose of Magic Powder":"MagicPowder",
			"Double Crow Bow":"CrowBow2",
			"Drag on-and-on Spell":"SpellDragon2",
			"Dueling Sabre":"DuelSword",
			"Duoacle":"P2",
			"ERROR(No type!)":"Bane.9165",
			"Eighth of the Moon":"EighthMoon",
			"Elevator Orange Sorbet":"IceCreamElevatorOrange",
			"Emerald Team Ring (Team Small Sand Worm)":"TeamRing.16940",
			"Empty Balloon":"Balloon",
			"Empty Book":"Book",
			"Empty Bottle":"Bottle",
			"Empty Cocktail Glass":"CocktailGlass",
			"Empty Jar":"Jar",
			"Empty Mug":"CoffeeCup",
			"Empty Vial":"Vial",
			"Enchant Air Sword Spell":"SpellSwordAir",
			"Enchant Earth Sword Spell":"SpellSwordEarth",
			"Enchant Fire Sword Spell":"SpellSwordFire",
			"Enchant Mud Spell":"SpellEnchantMud",
			"Enchant Silver Spell":"SpellSilverBox",
			"Enchant Water Sword Spell":"SpellSwordWater",
			"Enduring Strength Spell":"SpellDam4c",
			"Entangled Fleece":"EFleece",
			"Entangled Wool":"EWool",
			"Exotic Cocktail":"Cocktail",
			"Eye Pod":"EyePod.13525",
			"F.L.A. T-Shirt":"ShirtFLA",
			"Fast Defence Spell":"SpellArm4b",
			"Ferry (in a bottle)":"Ferry",
			"Fiddle":"InstrumentFiddle",
			"Filled Balloon":"NitroBalloon",
			"Fire-Ball Spell":"SpellFireBall",
			"First Aid Spell":"SpellHeal4a",
			"Fish":"BoringFish",
			"Fish-Fur Pelt":"FishFur",
			"Fistful of Almonds":"Almonds",
			"Flake Shaker":"FishFlakeDispenser",
			"Flash Gun (Flat)":"FlashGunBroken",
			"Fleeting Strength Spell":"SpellDam4a",
			"Fortune Cookie":"Cookie",
			"Fountain Pen":"Pen",
			"Four-Pack of Lager":"FourPack",
			"Frankenwiener Spell":"SpellRePet",
			"Frodo Cocktail":"HobbitCocktailFrodo",
			"Front 242 T-Shirt":"Shirt242",
			"Fruit Cake (aging)":"DryFruitCake.17119",
			"Full Defence Spell":"SpellArm4c",
			"Fungal Spray Spell":"SpellFungalSpray",
			"Fur Coat":"TribbleCoat",
			"Furious Bow":"CrossBow5",
			"Gandalf Cocktail":"HobbitCocktailGandalf",
			"Gas Bill":"ClueFourColour",
			"Glass of Absinthe":"Absinthe",
			"Glass of Polar Beer":"PolarBeer",
			"Glass of Wine":"Wine",
			"Glasses Spell":"SpellGlasses",
			"Glowing Mail On Sunday":"MailOnSunday",
			"Glowing Miners Hat":"LitMinersHat",
			"Glyph: Air":"GlyphAir",
			"Glyph: Antimony":"GlyphAntimony",
			"Glyph: Arsenic":"GlyphArsenic",
			"Glyph: Copper":"GlyphCopper",
			"Glyph: Earth":"GlyphEarth",
			"Glyph: Fire":"GlyphFire",
			"Glyph: Gold":"GlyphGold",
			"Glyph: Iron":"GlyphIron",
			"Glyph: Lead":"GlyphLead",
			"Glyph: Magnesium":"GlyphMagnesium",
			"Glyph: Mercury":"GlyphMercury",
			"Glyph: Salt":"GlyphSalt",
			"Glyph: Silver":"GlyphSilver",
			"Glyph: Sulphur":"GlyphSulphur",
			"Glyph: Tin":"GlyphTin",
			"Glyph: Water":"GlyphWater",
			"Gollum Cocktail":"HobbitCocktailGollum",
			"Gorgan-zola Sandwich":"GorganzolaSandwich",
			"Gram of Fairy Dust":"FairyDust",
			"Gram of Spice":"Spice",
			"Guide to Time and Space":"TimeGuide",
			"Guild Comms Room Kit":"GuildCommsKit",
			"Guild Decorator":"GuildBG",
			"Guild Locker":"GuildLock",
			"Guild Namer":"GuildName",
			"Guild Resignation Letter":"GuildResign",
			"Guild Ticket Office Kit":"GuildTurnstileKit",
			"Guild Trading Post Kit":"GuildTradeKit",
			"Guild Travel Node Kit":"GuildNodeKit",
			"Half of the Moon":"HalfMoon",
			"Hammer":"SmithHammer",
			"Hand Bell":"InstrumentHandBell",
			"Handful of Dough":"Dough",
			"Hard and Pointy Stick":"HardPointyStick",
			"Harmonica":"InstrumentHarmonica",
			"Harpsichord":"InstrumentHarpsichord",
			"Harvey's Bristol Cream":"BristolCream",
			"Hat Hunter Spell":"SpellHat",
			"Hat Trick Spell":"SpellHat2",
			"Head of the Gorgan":"GorganHead",
			"Hop East Spell":"SpellHopEast",
			"Hop North Spell":"SpellHopNorth",
			"Hop South Spell":"SpellHopSouth",
			"Hop West Spell":"SpellHopWest",
			"Huge Fire Cracker":"BigFireCracker",
			"Human Heart":"Heart",
			"Human Liver":"Liver",
			"Hurt 'em Lots Spell":"SpellDam10c",
			"Hurt 'em Spell":"SpellDam10b",
			"Hyper-Link":"HyperLink",
			"Impending Kick Spell":"SpellImpKick",
			"Impending Slap Spell":"SpellImpSlap",
			"Invisibility Spell":"SpellInvis",
			"Iron Hubbard":"Hubbard",
			"J&auml;ger Bomb":"JagerBomb",
			"Jar of Gas":"GasJar",
			"Jar of Grape Jam":"GrapeJam",
			"Jar of Plum Jam":"PlumJam",
			"Jewel of the Mountain King":"Jewel",
			"Jumper with holes":"JumperBad",
			"Jumper with many holes":"JumperWorse",
			"Kelley Spell":"SpellClear2",
			"Key (Duke Cor MDs Vault)":"VaultKey.10010",
			"Killing Blow Spell":"SpellDam10a",
			"Kings Crest Talisman":"KingsTalisman",
			"Kirk's Map":"EggMap",
			"Krosp Pez Dispenser":"PezDispenser.31147",
			"Lambs Liver":"LambLiver",
			"Leech":"Leech7",
			"Leech":"Leech2",
			"Leech":"Leech12",
			"Leech":"Leech9",
			"Leech":"Leech3",
			"Leech":"Leech5",
			"Leech":"Leech10",
			"Leech":"Leech11",
			"Leech":"Leech1",
			"Leech":"Leech4",
			"Leech":"Leech6",
			"Legolas Cocktail":"HobbitCocktailLegolas",
			"Length of Bunting":"Bunting",
			"Leprichawn Suit":"GreenSuit",
			"Loaf of Bread":"Bread",
			"Locate Spell":"SpellLocate",
			"Lump of Beeswax":"Beeswax",
			"Lump of Cactus Pulp":"CrushedCactus",
			"Lump of Mashed Beans":"MashedBeans",
			"Lump of Minced Beef":"MincedBeef",
			"Luncheon Truncheon":"LunchClub",
			"MOTD Spell":"SpellMOTD",
			"Magic Ball":"8Ball",
			"Magic Display Spell":"SpellDisplay",
			"Magic Mining Permit":"MiningPermit2",
			"Magic Scroll":"Video1",
			"Magical Aura Spell":"SpellLookWeird",
			"Major Healing Spell":"SpellHeal20b",
			"Map Spell":"SpellMap1",
			"Map Spell Extreme":"SpellMap3",
			"Map Spell Pro":"SpellMap2",
			"Map of Bognor":"BognorMap",
			"Map of Brighthelm":"BrightHelmMap",
			"Map of Earth City":"EarthMap",
			"Map of Fire City":"FireMap",
			"Map of Harvey Hall":"HarveyMap",
			"Map of Isle of Fright":"FrightMap",
			"Map of Water City":"WaterMap",
			"Map of Windy City":"AirMap",
			"Map of the Castle":"CastleMap",
			"Map of the Festival":"FestivalMap",
			"Map of the Forest":"DenMap",
			"Map to K.O.T. Keep":"KOTMap",
			"Map to the Hermit":"HermitMap",
			"Map to the Shrines":"ShrinesMap",
			"Marwell Talisman":"ZooTalisman",
			"Maybe Scarf":"QuantumScarf",
			"Measure of Black Powder":"BlackPowder",
			"Mini-K-A-M":"CustomWeapon.15476",
			"Minor Healing Spell":"SpellHeal10a",
			"Minty Python Ice Cream":"IceCreamMintyPython",
			"Misril Skin Spell":"SpellArm10c",
			"Miss A Bit Less Spell":"SpellHit20a",
			"More-Compressed Air Spell":"SpellWandAir2",
			"More-Compressed Earth Spell":"SpellWandEarth2",
			"More-Compressed Fire Spell":"SpellWandFire2",
			"More-Compressed Water Spell":"SpellWandWater2",
			"Mug of Ale":"Ale",
			"Mug of Coffee (decaf)":"DCoffee",
			"Mug of Coffee (proper)":"Coffee",
			"Mug of Ginger Beer":"GingerBeer",
			"Mug of Hot Chocolate":"HotChocolate",
			"Multicoloured Scarf":"Scarf",
			"Murder Bow":"CrowBow5",
			"Mysterious Envelope":"SealedTreasureMap",
			"Mystic Aim Spell":"SpellHit60b",
			"N'gann Potion":"PotionCure2",
			"Nightingbreeze Spell":"SpellMassHeal0",
			"Nightinggale Spell":"SpellMassHeal1",
			"Nightinghurricane Spell":"SpellMassHeal3",
			"Nightingstorm Spell":"SpellMassHeal2",
			"Norse/English dictionary":"NorseBook",
			"North-East Tunnel Map":"TunnelMapNE",
			"North-East Tunnel Talisman":"TunnelTalismanNE",
			"North-West Tunnel Map":"TunnelMapNW",
			"North-West Tunnel Talisman":"TunnelTalismanNW",
			"Old Bauhaus T-Shirt":"ShirtOldBauhaus",
			"Old F.L.A. T-Shirt":"ShirtOldFLA",
			"Old Front 242 T-Shirt":"ShirtOld242",
			"Old PWEI T-Shirt":"ShirtOldPWEI",
			"Old Pink PWEI T-Shirt":"ShirtOldPinkPWEI",
			"Old Ramones T-Shirt":"ShirtOldRamones",
			"Old Sex Pistols T-Shirt":"ShirtOldSexPistols",
			"Old Sisters of Mercy T-Shirt":"ShirtOldSisters",
			"Opal Team Ring (Team Small Sand Worm)":"TeamRing.16938",
			"PWEI T-Shirt":"ShirtPWEI",
			"Pair of Beer Goggles":"BeerGoggles",
			"Pair of Bunny Ears":"BunnyEars",
			"Pair of Daedalus Wings":"Wings",
			"Pair of Dr. Martins":"DrMartins",
			"Pair of Ear Muffs":"EarMuffs",
			"Pair of Firefly Trainers":"Trainers2",
			"Pair of Fishnets":"FishNets",
			"Pair of Heavy Boots":"HeavyBoots",
			"Pair of Holey Fishnets":"HoleyFishNets",
			"Pair of Holey Socks":"HoleySocks",
			"Pair of Knitting Needles":"KnittingNeedles",
			"Pair of Kraken Trainers":"Trainers3",
			"Pair of Magic Boots":"MagicBoots",
			"Pair of Pointy Boots":"PointyBoots",
			"Pair of Reading Glasses":"ReadingGlasses",
			"Pair of Rose-Tinted Shades":"RoseTintedShades",
			"Pair of Scissors":"Scissors",
			"Pair of Shades":"Shades",
			"Pair of Snow Goggles":"SnowGoggles",
			"Pair of Snowshoes":"Snowshoes",
			"Pair of Socks":"Socks",
			"Pair of Tongs":"Tongs",
			"Pair of Wellys":"Wellys",
			"Palantir-as-you-go":"OneShotPalantir",
			"Pan Pipes of Peace":"PanPipe",
			"Parcel (Parcel for Cor)":"Parcel.13417",
			"Pentacle":"P5",
			"Phoen Ice":"IceCreamPhoenIce",
			"Phoenix Feather":"PheonixFeather",
			"Piece of Ancient Wood":"OldWood",
			"Piece of Ash":"Ash",
			"Piece of Buttered Toast":"ButteredToast",
			"Piece of Cardboard":"Cardboard",
			"Piece of Chalk":"Chalk",
			"Piece of Hazel":"Hazel",
			"Piece of Holly":"Holly",
			"Piece of Honeycomb":"Honey",
			"Piece of Jammy Toast":"JammyToast",
			"Piece of Leather":"Leather",
			"Piece of Mail":"MailPiece",
			"Piece of Mutton":"Mutton",
			"Piece of Oak":"Oak",
			"Piece of Red Chalk":"RedChalk",
			"Piece of Rubber":"Rubber",
			"Piece of Soylent Green":"SoylentGreen",
			"Piece of Toast":"Toast",
			"Piece of Walnut":"Walnut",
			"Piece of Willow":"Willow",
			"Piece of Wood":"Wood",
			"Piece of Yew":"Yew",
			"Pigeon (In a cage)":"Pigeon",
			"Pinch of Salt":"Salt",
			"Pinhole Camera":"PinholeCamera.17726",
			"Pink PWEI T-Shirt":"ShirtPinkPWEI",
			"Pint of Blood":"Blood",
			"Pint of Cider and Black":"CiderAndBlack",
			"Pint of Cream":"Cream",
			"Pint of Fairy Liquid":"FairyLiquid",
			"Pint of Goat's Milk":"GoatMilk",
			"Pint of Milk":"Milk",
			"Pint of Sheep's Milk":"SheepMilk",
			"Plan for a Boat":"BoatPlan",
			"Plan for a Caravel":"CaravelPlan",
			"Plan for a Ferry":"FerryPlan",
			"Plan for a Raft":"RaftPlan",
			"Plan for a Survey Vessel":"SurveyVesselPlan",
			"Plan for a Virtuous Vessel":"VirtuousVesselPlan",
			"Plan for an Air Ship":"AirShipPlan",
			"Plans for a Speed Boat":"SpeedBoatPlan",
			"Plans for a Trawler":"TrawlerPlan",
			"Plans for a Zodiac":"ZodiacPlan",
			"Planter's Punch":"PlantersPunch",
			"Pocket Watch":"Watch",
			"Poison Apple Sorbet":"IceCreamPoisonApple",
			"Pop! Spell":"SpellPop",
			"Portion of Bangers and Mash":"BangersAndMash",
			"Portion of Chips":"Chips",
			"Portion of Mashed Potato":"MashedPotato",
			"Pot of Kraken Klaw Koleslaw":"Koleslaw",
			"Potion of Accuracy":"PotionToHit",
			"Potion of Healing":"PotionHeal",
			"Pouch of Magic Herb":"MagicHerb",
			"Pound of Poop":"Poop",
			"Proper Scarf":"TimeScarf",
			"Quad-Crow Bow":"CrowBow4",
			"Quadacle":"P4",
			"Quarter of the Moon":"QuartMoon",
			"Quick Shield Spell":"SpellArm2a",
			"Raft (in a bottle)":"Raft",
			"Raisin":"Rasin",
			"Ramones T-Shirt":"ShirtRamones",
			"Rampage Spell":"SpellDam2b",
			"Raze Spell":"SpellClear3",
			"Recall Spell":"SpellRecall",
			"Recipe Book":"RecipieBook",
			"Recovery Spell":"SpellHeal4c",
			"Remember Spell":"SpellRemember",
			"Rib (in a bottle)":"Rib",
			"Roasted Garlic Clove":"RoastedGarlic",
			"Roll of Film":"Film",
			"Rubber Helm":"QuantumHelm",
			"Ruby Team Ring (Team Small Sand Worm)":"TeamRing.16937",
			"Rusty Can of Wyrms":"CanOfWyrmsRusty",
			"Sabre-Toothed Tiger Shark":"STTigerShark",
			"Sacrificial Dagger":"SuckDagger",
			"Sacrificial Sword":"SuckSword",
			"Scrap of Vellum":"ClueCipher",
			"Screen (The Earth City Flower Show)":"CustomScreen.7438",
			"Screen Printing Kit":"ScreenKit",
			"Seal Fur Coat":"SealCoat",
			"Seal Fur Stole":"SealStole",
			"Seaweed Frond":"Seaweed",
			"Seaweed Surprise Ice Cream":"IceCreamSeaweedSurprise",
			"Second-Aid Spell":"SpellHeal8b",
			"Serving of Pasta":"Pasta",
			"Set of Steel Bars":"ClueBars",
			"Set of Water Wings":"WaterWings",
			"Sex Pistols T-Shirt":"ShirtSexPistols",
			"Sgt. Duke Cor MD Glasses":"MagicSpecs.43133",
			"Shaky Flake":"FishFlake",
			"Shanghorn Potion":"PotionCure3",
			"Shark Fin":"Fin",
			"Sharp Sword":"Sword",
			"Sheaf of Oats":"Oats",
			"Sheaf of Wheat":"Wheat",
			"Sheet of MDF":"MDF",
			"Sheet of Paper":"Paper",
			"Shell":"TankShell",
			"Shield Spell":"SpellArm2b",
			"Short String":"StringShort",
			"Short Wool":"WoolShort",
			"Shredded Bus Ticket":"CluePaperStrip",
			"Shredded Duck Bit":"ShreddedDuck",
			"Sign Post":"Sign",
			"Silver Puzzle Box":"SilverBox",
			"Single to The 'Kingdom":"SingleToKingdom",
			"Sisters of Mercy T-Shirt":"ShirtSisters",
			"Sixteenth of the Moon":"TeenthMoon",
			"Skip East Spell":"SpellSkipEast",
			"Skip North Spell":"SpellSkipNorth",
			"Skip South Spell":"SpellSkipSouth",
			"Skip West Spell":"SpellSkipWest",
			"Slice of Bacon":"Bacon",
			"Slice of Bread":"BreadSlice",
			"Slice of Crocodile Dundee Cake":"CrocodileDundeeCakeSlice",
			"Slice of Dundee Cake":"DundeeCakeSlice",
			"Slice of Flying Bacon":"FlyingBacon",
			"Slice of Tomato":"TomatoSlice",
			"Slice of Wedding Cake":"WCakeSlice",
			"Small Boat (in a bottle)":"Boat",
			"Smite Spell":"SpellDam100c",
			"Snap Spell":"SpellSnap",
			"Snowman":"SnowManKit",
			"Sod Spell":"SpellEarthBall",
			"Solid Gold Fiddle":"GoldFiddle",
			"Sorting Office Pass":"SortingPass",
			"South-East Tunnel Map":"TunnelMapSE",
			"South-East Tunnel Talisman":"TunnelTalismanSE",
			"South-West Tunnel Map":"TunnelMapSW",
			"South-West Tunnel Talisman":"TunnelTalismanSW",
			"Space Rocket":"Rocket",
			"Spartacus Mask":"SparticusMask",
			"Speed Boat, unpowered (in a bottle)":"SpeedBoatBroken",
			"Speedboat (in a bottle)":"SpeedBoat",
			"Speeder Bike, unpowered":"SpeederBikeBroken",
			"Spikey Ninja Throwing Star":"ThrowingStar",
			"Spotter's Guide":"TickBook",
			"Sprig of Mistletoe":"Mistletoe",
			"Stall Permit (11 items)":"StallPermit2",
			"Stall Permit (16 items)":"StallPermit3",
			"Stall Permit (6 items)":"StallPermit",
			"Stay on Target Spell":"SpellHit80c",
			"Stick of Butter":"Butter",
			"Strand of Silk":"Silk",
			"Strange Metal":"AlienMetal",
			"Stranger in a Strange Land (Hardback)":"Stranger",
			"Strength Spell":"SpellDam4b",
			"Summon Stone (cracked)":"CrackedSummonStone",
			"Super Invisibility Spell":"SpellInvis2",
			"Survey Vessel (in a bottle)":"SurveyVessel",
			"Survey Vessel, unnavigable (in a bottle)":"SurveyVesselBroken",
			"Syringe of Wolfsbane":"WolfCure",
			"T-Shirt":"Shirt",
			"T-Shirt (Dig My Grave Party)":"CustomShirt.7966",
			"T.G. Spell":"SpellTribbleGun",
			"Talisman (Golden Condor)":"Talisman.8067",
			"Tambourine":"InstrumentTambourine",
			"Teleport to Shop Spell":"SpellTeleportShop",
			"The Way of the Finger":"PokeyBook",
			"The art of Nasty Blows":"AirBook",
			"The art of the Flaming Punch":"FireBook",
			"The art of the Stone Fist":"EarthBook",
			"The art of the Wet Slap":"WaterBook",
			"Thick Skin Spell":"SpellArm1a",
			"Thieves' Talisman":"ThievesTalisman",
			"Third-Aid Spell":"SpellHeal16c",
			"Toad Spell":"SpellToad",
			"Toadvine Potion":"PotionCure7",
			"Toy Unicorn":"Unicorn",
			"Trainspotter's Guide":"TrainBook",
			"Trawler (in a bottle)":"Trawler",
			"Trawler with hole (in a bottle)":"TrawlerHoled",
			"Tray of Curry":"Curry",
			"Treasure Chest":"Treasure",
			"Treasure Hunt List":"TreasureList",
			"Treasure Map (Peach Beards Treasure)":"TreasureMap.26203",
			"Tri-Crow Bow":"CrowBow3",
			"Triacle":"P3",
			"Triangle":"Instrument",
			"Triffid Sting":"Poison",
			"Trill Potion":"PotionCure5",
			"Uncertain Egg":"SheepEgg",
			"Uncertain Jumper":"QuantumJumper",
			"Unit of Charcoal":"Charcoal",
			"Unit of Enchanted Charcoal":"EnchantedCharcoal",
			"Unit of Glue":"Glue",
			"Unit of Sand":"Sand",
			"Unwrapped Gift":"Gift.8031",
			"Vashka":"IceCreamTheVashka",
			"Vial of Lanolin":"Lanolin",
			"Vial of Salad Dressing":"Dressing",
			"Vial of Suncream":"Suncream",
			"Viol":"InstrumentViol",
			"Virtuous Vessel (in a bottle)":"VirtuousVessel",
			"Virtuous Vessel with hole (in a bottle)":"VirtuousHoled",
			"Vitality Spell":"SpellHeal2b",
			"Vitsee Potion":"PotionCure9",
			"Void Calling Spell":"SpellTimeWarp",
			"Wad of Raw Wool":"CardedWool",
			"Wand of Anger":"AngryWand",
			"Wand of Convincing Illusion":"IllWand2",
			"Wand of Illusion":"IllWand",
			"Wand of Trading":"TradingWand",
			"Warrior's Totem":"WarriorsTotem",
			"Water Bomb Spell":"SpellWaterBall",
			"Water Walking Spell":"SpellWWalk",
			"Wax Tablet":"ClueSimEq",
			"Week End Spell":"SpellTimeWarp2",
			"Wellbeing Spell":"SpellHeal1a",
			"White Egg":"ElephantEgg",
			"White Sheet":"Sheet",
			"Whole of the Moon":"Moon",
			"Winged Boot":"FlyingBoot",
			"Wizards Retreat Spell":"SpellRetreat",
			"Wombat Spell":"SpellWombat",
			"Wool":"WoolNormal",
			"Wormhole Entrance (Pink)":"WormholeIn.11745",
			"Wormhole Exit (Pink)":"WormholeOut.11746",
			"Wyrm Spell":"SpellDragon",
			"Zephyr Spell":"SpellAirBall",
			"Zodiac with hole (in a bottle)":"ZodiacHoled"
		}		
	}
	if (internals[itemName]) return internals[itemName];
	else return itemName.replace(/ /g,'');
}

function isUsable(item) {
	if (!usableEquip) {
		usableEquip={"8Ball":true,"Absinthe":true,"SummonStone":true,"BronzeAxe":true,"IronAxe":true,"MisrilAxe":true,"SilverAxe":true,"StoneAxe":true,"AirBook":true,"AirLollipop":true,"AirBow":true,"AirCatana":true,"AirKnife":true,"AirStone":true,"AirSword":true,"AirSword2":true,"AirTalisman":true,"AirWand":true,"AirWand2":true,"AirWand3":true,"Anisette":true,"ArenaTalisman":true,"AstralTalisman":true,"Bacon":true,"BaconSandwich":true,"Bandage":true,"BangersAndMash":true,"BarbelithTalisman":true,"BigFireCracker":true,"BlankTalisman":true,"Blood":true,"BLTSandwich":true,"BluePill":true,"Booze":true,"BottleWine":true,"BowlingPermit":true,"Brandy":true,"BrighthelmRock":true,"Bunting":true,"Butter":true,"ButteredToast":true,"Cake":true,"Candle":true,"CanOfWorms":true,"CanOfWyrms":true,"CanOfWyrmsCrushed":true,"CanOfWyrmsRusty":true,"CanOfX":true,"ChickenSoup":true,"ChinaSet":true,"ChocolateBunny":true,"ChocolateEgg":true,"ChocolateMudslide":true,"Cigar":true,"ClockworkOrange":true,"Coffee":true,"CoffeeBeans":true,"Cookie":true,"Cream":true,"CrispyDuck":true,"CrocodileDundeeCake":true,"CrocodileDundeeCakeSlice":true,"CucumberSandwich":true,"CucumberSlice":true,"Currency":true,"Curry":true,"Curse":true,"DCoffee":true,"DebugStick":true,"DojoTalisman":true,"Dough":true,"DragonBlood":true,"Drink":true,"DundeeCake":true,"DundeeCakeSlice":true,"DX":true,"E":true,"EarthBook":true,"EarthLollipop":true,"Egg":true,"EmergencyFlare":true,"EmptyPinholeCamera":true,"Enlightenment":true,"EvilRoot":true,"Fag":true,"FireBook":true,"FireCracker":true,"FireLollipop":true,"Fireworks":true,"FizzyWine":true,"FlashGun":true,"Flux":true,"FluxCapacitor":true,"FlyingBacon":true,"FlyingBaconSandwich":true,"Food":true,"ForbiddenTalisman":true,"FourPack":true,"FruitCake":true,"Garlic":true,"Gherkin":true,"GiftBox":true,"Gin":true,"GinAndTonic":true,"GingerWine":true,"Goody":true,"Gorganzola":true,"GorganzolaSandwich":true,"GrapeJam":true,"Grapes":true,"Grog":true,"GroundCoffee":true,"GuildKit":true,"GuildLock":true,"GuildPermit":true,"GuildResign":true,"Heart":true,"HeartShapedBox":true,"Herb":true,"Herb20":true,"Herb21":true,"Herb22":true,"Herb23":true,"Herb25":true,"Herb26":true,"HerbLiqueur":true,"HillFortPermit":true,"HotChocolate":true,"Hubbard":true,"Humidor":true,"HyperLink":true,"IceCream":true,"IceCreamChocolateBombe":true,"IceCreamElevatorOrange":true,"IceCreamMintyPython":true,"IceCreamPhoenIce":true,"IceCreamPoisonApple":true,"IceCreamSeaweedSurprise":true,"IceCreamSloeDjinn":true,"IceCreamTheVashka":true,"IllWand":true,"IllWand2":true,"InverseTimeWarp":true,"IvoryTusk":true,"JagerBomb":true,"JammyToast":true,"JournalistsKit":true,"JunkFood":true,"Kahlua":true,"KingsTalisman":true,"Kipple":true,"Koleslaw":true,"KrakenPiece":true,"Lager":true,"LavaBomb":true,"Lettuce":true,"LettuceLeaf":true,"LimboTalisman":true,"Lollipop":true,"MagicCookie":true,"MagicCookieJar":true,"MagicHerb":true,"MagicMud":true,"MagicPowder":true,"MallTalisman":true,"MashedBeans":true,"Matches":true,"MincedBeef":true,"MiniBar":true,"MiningPermit":true,"MiningPermit2":true,"Mistletoe":true,"MixedSalad":true,"MockworkOrange":true,"Mutton":true,"NewAnimalCarrier":true,"NewBag":true,"NewCabinet":true,"NewEyePod":true,"NitroBalloon":true,"NorthernRock":true,"NorthwichTalisman":true,"Nuke":true,"Onion":true,"OnionRing":true,"P5":true,"PandorasSocks":true,"Pants":true,"PartyFixings":true,"PartyPack":true,"PepperSauce":true,"PhwAmulet":true,"PickleSlice":true,"PicnicBasket":true,"Plinth":true,"PokeyBook":true,"PortableFluxCapacitor":true,"PortalMaker":true,"Potato":true,"PotionCureAbstract":true,"PotionHeal":true,"PotionToHit":true,"PrimaryKey":true,"PrimordialSoup":true,"QueensInACan":true,"Rasin":true,"RedBull":true,"RedPill":true,"ReverseTimeWarp":true,"Rig":true,"RingPull":true,"RoastedGarlic":true,"Rocket":true,"RoddenBerry":true,"RomulanAle":true,"Rose":true,"RoseQuartz":true,"RubySlipper":true,"Rum":true,"SaurianBrandy":true,"Scone":true,"SealedTreasureMap":true,"Serenity":true,"Sextant":true,"ShopPermit":true,"ShreddedDuck":true,"Sign":true,"SloeGin":true,"SmokeBomb":true,"Snark":true,"SnowManKit":true,"SoylentGreen":true,"StallPermit":true,"StallPermit2":true,"StallPermit3":true,"StoneIdol":true,"StrangePowder":true,"Stranger":true,"SunFlower":true,"Talisman":true,"Tea":true,"Tequila":true,"ThievesTalisman":true,"TimeWarp":true,"TomatoSlice":true,"Treasure":true,"Trebuchet":true,"TribblePelt":true,"TripleSec":true,"TunnelTalisman":true,"Unicornucopia":true,"Use":true,"VaultPermit":true,"VaultTalisman":true,"VenueMaker":true,"Vodka":true,"Water":true,"WaterBook":true,"WaterLollipop":true,"WCake":true,"WCakeSlice":true,"WhippedCream":true,"Whisky":true,"WhiteRussian":true,"WormholeKit":true,"ZooTalisman":true,"WhiteRussian":true,"BloodyMary":true,"VodkaMartini":true,"Mule":true,"Wallbanger":true,"DryMartini":true,"GinAndTonic":true,"SloeGinFizz":true,"TomCollins":true,"Gimlet":true,"EggNog":true,"ChampagneCocktail":true,"BrandyAlexander":true,"Stinger":true,"Manhattan":true,"MintJulep":true,"WhiskyMac":true,"Sazerac":true,"BrownCow":true,"Grasshopper":true,"Mojito":true,"PlantersPunch":true,"Daiquiri":true,"Zombie":true,"PinaColada":true,"TequilaSlammer":true,"Margherita":true,"TequilaSunrise":true,"Cockroach":true,"AbstractEgg":true,"ChocolateEgg":true,"DragonEgg":true,"DungEgg":true,"Egg":true,"ElephantEgg":true,"FerretEgg":true,"GoldenEgg":true,"GoldFishEgg":true,"GooseEgg":true,"HamsterEgg":true,"KittinEgg":true,"MagicEgg":true,"MayflyEgg":true,"MinrilaxEgg":true,"PeeveEgg":true,"PwnyEgg":true,"SheepEgg":true,"StoneEgg":true,"AlignTalisman":true,"ArenaTalisman":true,"AstralTalisman":true,"BarbelithTalisman":true,"BlankTalisman":true,"DojoTalisman":true,"ForbiddenTalisman":true,"KingsTalisman":true,"LimboTalisman":true,"MallTalisman":true,"NorthwichTalisman":true,"Talisman":true,"ThievesTalisman":true,"TunnelTalisman":true,"VaultTalisman":true,"ZooTalisman":true,"EarthBow":true,"EarthCatana":true,"EarthKnife":true,"EarthStone":true,"EarthSword":true,"EarthSword2":true,"EarthTalisman":true,"EarthWand":true,"EarthWand2":true,"EarthWand3":true,"FireBow":true,"FireCatana":true,"FireKnife":true,"FireStone":true,"FireSword":true,"FireSword2":true,"FireTalisman":true,"FireWand":true,"FireWand2":true,"FireWand3":true,"WaterBow":true,"WaterCatana":true,"WaterKnife":true,"WaterStone":true,"WaterSword":true,"WaterSword2":true,"WaterTalisman":true,"WaterWand":true,"WaterWand2":true,"WaterWand3":true,"NeutralBow":true,"NeutralCatana":true,"NeutralKnife":true,"NeutralStone":true,"NeutralSword":true,"NeutralSword2":true,"NeutralTalisman":true,"NeutralWand":true,"NeutralWand2":true,"NeutralWand3":true,"NeutralBow":true,"NeutralCatana":true,"NeutralKnife":true,"NeutralStone":true,"NeutralSword":true,"NeutralSword2":true,"NeutralTalisman":true,"NeutralWand":true,"NeutralWand2":true,"NeutralWand3":true,"SpiritBow":true,"SpiritCatana":true,"SpiritKnife":true,"SpiritStone":true,"SpiritSword":true,"SpiritSword2":true,"SpiritTalisman":true,"SpiritWand":true,"SpiritWand2":true,"SpiritWand3":true,"IceBow":true,"IceCatana":true,"IceKnife":true,"IceStone":true,"IceSword":true,"IceSword2":true,"IceTalisman":true,"IceWand":true,"IceWand2":true,"IceWand3":true,"ShrimpBow":true,"ShrimpCatana":true,"ShrimpKnife":true,"ShrimpStone":true,"ShrimpSword":true,"ShrimpSword2":true,"ShrimpTalisman":true,"ShrimpWand":true,"ShrimpWand2":true,"ShrimpWand3":true,"SewageBow":true,"SewageCatana":true,"SewageKnife":true,"SewageStone":true,"SewageSword":true,"SewageSword2":true,"SewageTalisman":true,"SewageWand":true,"SewageWand2":true,"SewageWand3":true,"DarkBow":true,"DarkCatana":true,"DarkKnife":true,"DarkStone":true,"DarkSword":true,"DarkSword2":true,"DarkTalisman":true,"DarkWand":true,"DarkWand2":true,"DarkWand3":true,"GothBow":true,"GothCatana":true,"GothKnife":true,"GothStone":true,"GothSword":true,"GothSword2":true,"GothTalisman":true,"GothWand":true,"GothWand2":true,"GothWand3":true,"PureBow":true,"PureCatana":true,"PureKnife":true,"PureStone":true,"PureSword":true,"PureSword2":true,"PureTalisman":true,"PureWand":true,"PureWand2":true,"PureWand3":true};
	}
	return usableEquip[item]?(true):(false);
}
